version: '3'

services:
  mysql:
    image: mysql:8.0.32
    environment:
      #- MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    restart: unless-stopped
    ports: 
      - "3306:3306" # host_port:container_port
    container_name: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"