version: '3'

services:
  mysql:
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: unless-stopped
    container_name: mysql
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      timeout: 20s
      retries: 10
      
  redis:
    image: redis:7.0.12
    restart: unless-stopped
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      timeout: 20s
      retries: 10

  server:
    image: microblog
    container_name: microblog
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  nginx:
    image: nginx:1.25.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8099:80
    container_name: reverse-proxy
    depends_on:
      - server

